### PR TITLE
initial `cityseer` thoughts

### LINKED ISSUE #2: Get cityseer workflow
* [x] ~~choose small AOI with edge cases~~ Cases set in #16, etc.
  * [x] ~~Apalachicola, FL?~~
  * [x] ~~Ortigia, IT?~~
  * [x] ~~St. Gallen, CH?~~
  * [x] ~~other?~~
* [x] review [`cityseer`](https://cityseer.benchmarkurbanism.com/)
  * [x] [docs](https://cityseer.benchmarkurbanism.com/intro)
  * [x] [Examples](https://cityseer.benchmarkurbanism.com/examples#examples)
  * [x] [OSM and NetworkX](https://cityseer.benchmarkurbanism.com/guide#osm-and-networkx)
  * [x] [GeoPandas](https://cityseer.benchmarkurbanism.com/guide#geopandas) – mentions `momepy`
  * [x] etc
* [x] play around with package & create notebook
  * [x] explore functionality
  * [x] demo use case
  * [x] put into function
    * in: `geopandas.GeoDataFrame` of `shapely.LineString` objects
    * out: `geopandas.GeoDataFrame` of `shapely.LineString` objects

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR kicks off the `cityseer` explorations. Please provide any thoughts/feedback/recommendations. See [here](https://gist.github.com/jGaboardi/582dc1f207054a861eda93e975713b4b) for gist version of the notebook in this PR.

xref:
* #1 
* #2 
* (maybe) closes #2

### CODE REVIEW

**Review by anastassiavybornova — APPROVED** [review]
looks good to me! well, good in the sense of - great to start playing around with this one - maybe less good for the purposes that we hoped it would serve. i'll make a pull request with some test data from our previous ("bananas") project ([this one](https://github.com/martinfleis/urban-block-artifacts)) , my next question for cityseer here is: what if we only have a geodataframe of linestrings (no OSM attributes etc), is that still a valid input for the simplification functions? i hope so (would be nice to compare for the same data sets across packages)

**Comment by jGaboardi** [comment]
> my next question for cityseer here is: what if we only have a geodataframe of linestrings (no OSM attributes etc), is that still a valid input for the simplification functions

Good point.

**Comment by jGaboardi** [comment]
@anastassiavybornova Should I move this notebook into the `code/` directory (like yours)? Or should we move yours into this `notebooks/` repo?

cc @martinfleis

**Comment by martinfleis** [comment]
I'd vote for `code` as @anastassiavybornova did it.

**Comment by jGaboardi** [comment]
> I'd vote for `code` as @anastassiavybornova did it.

Sounds good. I'll update the location in this PR, as well as test with the standard data.

**Comment by jGaboardi** [comment]
#### Cityseer redeaux

* next attempt at understanding `cityseer` somewhat based on @anastassiavybornova's stuff
* very much a work in progress... just wanted to give an update 
* will need much love and care
* initial thoughts from yall are very welcome

**Comment by jGaboardi** [comment]
***Cityseer threedeaux***

* @anastassiavybornova & @martinfleis – I made some pretty big updates & streamlines to the directory and infrastructure here. Please let me know if it's too much at once.
* Basically, added a dedicated 311 and 312 envs files, we should be able to use 312 now. CitySeer updated since I started using it. Also, worked out the `opencv` / `condaforge stuff.
* CItySeer is still a monster. The notebook I added to go through simplification step by step to demonstrate the graph elements at each stage. And I provide some PNGs in `usecases/809/cityseer/` to visualize (not as cool as @anastassiavybornova's fancy gifs).
* LOTS can be done in terms of parameterizes within `cityseer`. Let me know if there is something specific to hone in on.

**Pull request merged**
