### PR TITLE
curate non-articulation node roads

### LINKED ISSUE #82: [data] parquet files with non-articulation nodes removed
xref: https://github.com/uscuni/simplification/pull/80#pullrequestreview-2140824961

Proposed structure:

```
-- data
    | -- 1133
    |    | -- no_degree_2
    |    |    | -- 1133.parquet
```

Any better suggestions?

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR:
* resolves #82 
* provides a convenience reader in `utils.py`
* adds test for the reader
* fills out some testing for the other readers already present
* xref #80

### CODE REVIEW

**Comment by martinfleis** [comment]
We should also have a reproducible code generating these.

**Comment by jGaboardi** [comment]
> We should also have a reproducible code generating these.

Do we think:
1. simply having a generic function in `utils` (or somewhere else) that generates a non-articulation nodes network?
2. having a function that specifically generates the non-articulation nodes networks for our FUAs.?
3. some combination of 1&2 to also saves out the data?
4. a notebook that does this?

**Comment by anastassiavybornova** [comment]
i would suggest:
* having a generic function (will be useful!!) PLUS
* having a notebook with input: `roads_osm.parquet` subfolders, and output: `no_degree_2` subfolders
(notebook would be a very short one, but i think it's cleaner like this - we can possibly later merge it, if we find out that there is more data preprocessing to do, e.g. as we figured out with COINS yesterday, we will need a workflow step to remove (partially) overlapping linestrings *before* we run coins on the gdfs)

**Comment by jGaboardi** [comment]
> articulation nodes

*non* articulation nodes are degree 2 nodes in general - nodes in a graph where traversal decisions are not affected by their removal. Interstitial & non-articulation are interchangeable terms.

> are self-loops allowed? if so, are we keeping or removing them when we drop degree2 nodes? i'm thinking about a "lollipop" shape, where the head of the lollipop is a selfloop (or would a self-loop at the lollipop stick result in a degree3 node? confusion)

hmmmm. That would inside [`momepy.remove_false_nodes()`](https://github.com/pysal/momepy/blob/b9ae7f24883508df4d3e5cbcaa1071e1a60d84b2/momepy/preprocessing.py#L166). It's a good question and not immediately clear from reading the code. @martinfleis Do you know if this is the case?

**Comment by martinfleis** [comment]
I meant only a notebook calling `momepy.remove_false_nodes` on input and saving these files. Otherwise this step is undocumented. 

Not sure about self loop handling, will need to check once I'll be back at laptop.

**Comment by jGaboardi** [comment]
I have already include a function in `utils` in the meantime, along with a test. Shall I remove?

@anastassiavybornova Do have a known loop road case? If so, I can test that right now.

**Comment by martinfleis** [comment]
Can you push that function? I'm not sure what it does :). I don't mind having it but we need a notebook documenting this processing step.

**Comment by jGaboardi** [comment]
> Can you push that function? I'm not sure what it does :)

Absolutely, it merely wraps `momepy.remove_false_nodes()`

**Comment by jGaboardi** [comment]
@anastassiavybornova & @martinfleis this is ready for re-review.

**Comment by jGaboardi** [comment]
(I think)

**Review by martinfleis — APPROVED** [review]
Thanks!

I would just probably use `momepy.remove_false_nodes(read_parquet_roads(fua))` in the notebook over defining its own wrapper function for better transparency but that is nearly irrelevant.

**Comment by anastassiavybornova** [comment]
@martinfleis @jGaboardi putting this here since we were discussing above:

re self-loops (and btw also re multi edges), i've tried to look into it a bit:
* for the self-loops, i think there are usually none in the "raw" data (before removing d2 nodes) but lots of them appear once d2 nodes are removed (i checked for Liège and there are almost 100) - they can easily be found with the `nx.selfloop_edges` generator. (instead of pointing you to a particular use case). i don't think that it's a problem in general (and certainly not for COINS since it's working with geometries) but we should def keep this in mind if we want to do anything with the graph later on.
* for the multi edges (the ones that were creating chaos in COINS what we checked during our last discussion): one workaround would be to do `mm.gdf_to_nx` and then remove all multiedges that have keys > 0 (making sure that their geometries are already represented). but not sure if we do need to go all the way into graph creation and back for that, maybe there's an easier way?

**Comment by martinfleis** [comment]
multi-edges are fine, duplications are an issue. It seems that a sequence of `normalize` and `duplicated` should be able to solve most of them. 

> remove all multiedges that have keys > 0

Each edge can have its own geometry. Not a good idea imho.

**Comment by anastassiavybornova** [comment]
@martinfleis agree ofc! (that's also why i said "making sure that their geometries are already represented" 😅 ) for Liège, *all* of the multiedges with key 1 were duplicated geometries of edges with key 0. ofc one would need to verify whether that is the case or not. but i think your suggestion of using `normalize` and `duplicated` would take care of that issue in a more straightforward way (prior to graph creation). do we need an issue for including `normalize` and `duplicated` in our preprocessing workflow? (so that the weird error you showed us last time is avoided)

**Comment by martinfleis** [comment]
> do we need an issue for including normalize and duplicated in our preprocessing workflow?

yes

**Pull request merged**
