### PR TITLE
update cityseer and osmnx files using the pixi env versions

### LINKED ISSUE #198: update `cityseer` data
* xref: https://github.com/uscuni/simplification/issues/192
* rerun the `cityseer` data with the latest package version before "final" analysis.
* review any differences between the `cityseer` guidelines from `4.15.2` and whichever version is latest
   * currently `4.17.1` at the time of this writing
* use defaults like before, no OSM tags stuff that the newer `cityseer` versions are highly reliant on

### PR DESCRIPTION
**Pull request by martinfleis**
Closes #198

This uses the locked environment from #207 to re-run osmnx and cityseer simplification routines for the sake of reproducibility. 

@jGaboardi is our observation correct when we concluded that the workflow we have for cityseer now divereges from the workflow they use internally? Why is that?

### CODE REVIEW

**Comment by jGaboardi** [comment]
> @jGaboardi is our observation correct when we concluded that the workflow we have for cityseer now divereges from the workflow they use internally? Why is that?

I have not had the chance to confirm if it actually diverges. My initial look at the guidelines was that the document layout was significantly different than it had been. But adding in all the OSM tags stuff there could likely account for that.

**Comment by martinfleis** [comment]
I don't mean that it diverges from the user guide but from the implementation that is used within the io module you unpacked in the beginning.

A side observation - new version makes less changes that the old one with the default parameters in SLC.

**Comment by jGaboardi** [comment]
> I don't mean that it diverges from the user guide but from the implementation that is used within the io module you unpacked in the beginning.

Yeah same. I just haven't have a chance to dig into that yet.

**Comment by martinfleis** [comment]
Okay. Let's merge the current version and then we can revise the implementation later.

**Review by jGaboardi — APPROVED** [review]

**Pull request merged**
