### PR TITLE
drop service roads from road networks

### PR DESCRIPTION
**Pull request by martinfleis**
I pulled the original data from [martinfleis/urban-block-artifacts](https://github.com/martinfleis/urban-block-artifacts), replaced the existing in our `original/data` folders, adapted clipping notebook so it also removes service roads and executed it, replacing the data with clipped extent with no service roads. Then I also executed the notebook removing nodes of degree 2.

This is super annoying for the manual simplification which should've been done based on this input but was done based on the one that included service roads, so we'll need to find a way of removing what used to be a service road from the already finished manual roads. 

@anastassiavybornova can you please verify that these networks are in all cases indeed subsets we really want to use? I have done that myself but I would like to have a proper review here.

### CODE REVIEW

**Comment by martinfleis** [comment]
Tests need to be updated to match the updated data.

Also, parenx will need to be updated as well. 

I am not planning on doing any of that now.

**Comment by anastassiavybornova** [comment]
@martinfleis i checked for all the cities, for each of them comparing the `original` data set on this branch with 2 networks downloaded from OSM (as of today):

* `ox.graph_from_polygon`with network type `all` (this then includes all service roads)
* `ox.graph_from_polygon` with custom_filter : `'["highway"~"living_street|motorway|motorway_link|pedestrian|primary|primary_link|residential|secondary|secondary_link|tertiary|tertiary_link|trunk|trunk_link|unclassified"]'` (i.e. the one we used [here](https://github.com/martinfleis/urban-block-artifacts/blob/main/code/01_download.ipynb) but without `service`)

and i can confirm that the data sets on this branch coincide with the second one (with some minor discrepancies, but i guess that's due to the time that has passed since) so yes, these are the subset we want to use

**Comment by anastassiavybornova** [comment]
i can take care of the `parenx` update once this is merged

**Comment by martinfleis** [comment]
Thanks!

**Pull request merged**
