### PR TITLE
first draft of typology

### PR DESCRIPTION
**Pull request by anastassiavybornova**
i've made this in keynote (not very friendly, i know, but this is just a first draft - we can switch to another format if you want to play around with this collaboratively, maybe the best would be having a proper jupyter notebook with some matplotlib illustrations?) 

the main idea behind the typology is:
* we first classify the artifact as x-node (3, 4, 5...) - this also means x-edge (3, 4, 5...)
* we assume that each of the x edges is its own continuity group (i'm realizing now that this is not always true, as Martin said, so this needs to be refined)
* we classify each of the edges as either: 
* "beginning AND ending at the artifact" (calling them *single (S)*); 
* "beginning before but ending at the artifact [disregarding directionality]" (i'm calling them *ending (E)* )
* "beginning before and continuing after the artifact" (calling them *continuous (C)*)

So each x-node artifact is a combination of length x of the letters C, E, S (drawn with replacement); and there are some symmetries since we only care about the order; e.g. CECS == SCEC == CSCE (reading the 4 edges one after the other, it doesn't matter at which letter you start to read and in which direction you go)

@martinfleis i did this *before* looking again at the triangle notebook, and i found almost all of your cases (while you found almost all of mine) :) with the caveat that i haven't yet considered that we could have less than x continuity groups at each artifact

### CODE REVIEW

**Comment by martinfleis** [comment]
This is cool. I would try to expand our detection functions to catch them in the actual network. In some cases I struggle a bit to imagine a network _beyond_ the artefact that would allow such a configuration.

**Comment by anastassiavybornova** [comment]
@martinfleis my next step would be to refine the typology by saying that there can be up to x different continuity groups (strokes) at each x-node artifact (instead of assuming that there are exactly x ones) - which would add more use cases indeed (some of which can maybe be treated the same way) - any thoughts? does that make sense?

**Comment by martinfleis** [comment]
Yes, it does as those do happen.

**Comment by jGaboardi** [comment]
Should we mark this PR as ***Draft*** for now

**Comment by anastassiavybornova** [comment]
updated typology:
* introduced subcategories by number of strokes in artifact boundary
* clarified & added strokes that create "additional" nodes (e.g. for 4-node 3-continuity - the 4th node is from an edge that ends on the artifact boundary without delineating it)

**Comment by anastassiavybornova** [comment]
closing for clean up purposes, i have the "old" keynote file saved locally too, and it's outdated anyways

**Pull request closed without merging**
