### PR TITLE
all `code/utils.py` to `core/*` && `evaluate_h3cells` overhaul

### LINKED ISSUE #60: (slowly) emulate functionality in `code` --> `core` + test
(slowly) emulate functionality in `code` --> `core` + test

* `code/`
  * `utils.py` – #54
    * [x] `city_fua`
    * [x] `fua_city`
    * [x] `read_sample_data`
    * [x] `read_parquet_roads`
    * [x] `graph_size`
    * [x] `load_usecases`
  * `viz/` – #61
      *  `context.py`
         * [x] `path`
         * [x] `location`
         * [x] `param_plot`
         * [x] `video`
  * .... 
  * etc... 

xref #38, #54

### LINKED ISSUE #62: add Ana's util func to __all__ & migrate to `core.util.py`
* ~~add Ana's util func to `__all__`~~
* move Ana's stuff directly in `core/*` 
* migrate to `core.util.py`

xref #60, #66

### PR DESCRIPTION
**Pull request by jGaboardi**
This is a hefty PR that:
* moves all the functionality within `code/utils.py` to `core/*`
  * DRYs & enhances robustness
  * hex creation --> `core.utils.py`
  * stat analysis, etc. --> `core.stats.py`
  * plotting --> `core.viz.h3_hex.py`
* overhauls `evaluate_h3cells` functionality within `code/`
  * @anastassiavybornova one "major" change is that Hex cells can be isolated and plotted by `hex_id` -- more robust than index location
* tests for everything
* updates README
* xref #63 
* resolves #62 
* resolves #60

### CODE REVIEW

**Comment by martinfleis** [comment]
I will let @anastassiavybornova review this one as it mostly touches her code.

**Comment by jGaboardi** [comment]
> I will let @anastassiavybornova review this one as it mostly touches her code.

LOL Okay lazy bones.

**Comment by jGaboardi** [comment]
@martinfleis I think we'll actually want you eyes on a couple things for performance that @anastassiavybornova had mentioned when she made her original PR for this stuff. While I have reproduced her outputs (mostly) faithfully with some improved performance there is still the outstanding use of `apply` in cell 10 of [`evaluate_h3cells.ipynb`](https://github.com/uscuni/simplification/blob/c44d6b4f711362876f4b02d563e5cfa4346a444c/notebooks/evaluate_h3cells.ipynb) as it relates to [`get_edge_stats()`](https://github.com/uscuni/simplification/blob/c44d6b4f711362876f4b02d563e5cfa4346a444c/core/stats.py#L36) and [`get_edge_stats()`](https://github.com/uscuni/simplification/blob/c44d6b4f711362876f4b02d563e5cfa4346a444c/core/stats.py#L68) in `core/stats.py`

**Comment by martinfleis** [comment]
It looks okay to me. Is there some performance issue? Does it take hours or anything?

**Comment by jGaboardi** [comment]
> It looks okay to me. Is there some performance issue? Does it take hours or anything?

OK, cool. For Auckland that notebook cell takes ≈2 seconds to run. I wasn't sure if there was some easy adjustment or clever spatial join that could be done to cut that time. At any rate, I think good enough for now and we can revisit if it becomes a problem with larger AOIs.

**Comment by martinfleis** [comment]
If it took 20 minutes I would hesitate if it is worth any further attention. At 2s, you spend more reading this comment than what would you save in the end.

**Review by anastassiavybornova — APPROVED** [review]
Looks good to me, thanks James for the housekeeping as always <3 and yes sure, agree for the performance, if there's no palpable issue let's just leave the `.apply` (well, now it's `.map`) inside the `stats` functions

**Pull request merged**
