### PR TITLE
add outputs of manual simplification

### PR DESCRIPTION
**Pull request by martinfleis**
ref #70 

@jGaboardi this may not be optimal format or placement. Feel free to move them around if you prefer different setup, I am just dumping here what I got.

### CODE REVIEW

**Comment by jGaboardi** [comment]
@anastassiavybornova Do you have any opinions on where this data should be stored? Do you think the current pathing Martin implemented here is sufficient?

**Comment by anastassiavybornova** [comment]
how about having subfolders for each method's output? so `{fuaID}/{method}/output.gpkg`, where one of the {method} subfolders will be `manual` (and others: parenx, osmnx, ...)

**Comment by jGaboardi** [comment]
> how about having subfolders for each method's output? so `{fuaID}/{method}/output.gpkg`, where one of the {method} subfolders will be `manual` (and others: parenx, osmnx, ...)

Good idea. It fits the current schema. I'll pull down and make changes locally.

**Comment by jGaboardi** [comment]
@martinfleis @anastassiavybornova 

For some FUA's there is already a `manual/` directory with a `.parquet` inside. For example, [`data/1133/manual/`](https://github.com/uscuni/simplification/tree/main/data/1133/manual)...

**Comment by martinfleis** [comment]
> For some FUA's there is already a manual/ directory with a .parquet inside

we should probably follow that

**Comment by jGaboardi** [comment]
> > For some FUA's there is already a manual/ directory with a .parquet inside
> 
> we should probably follow that

I will:
* check to ensure the `.parquet` versions are the same data as the `.gpkg` ones
* convert the `.gpkg` to `.parquet` where there is no `.parquet`

Any thing else to think about here?

**Comment by martinfleis** [comment]
That's probably it

**Comment by jGaboardi** [comment]
> check to ensure the `.parquet` versions are the same data as the `.gpkg` ones

If I find any differences I'll report back here.

**Comment by anastassiavybornova** [comment]
archeology details: that was me who uploaded the .parquet ones, at some earlier iteration (for the feature matching). i got them from the gdrive and extracted only the "final version" layer before saving to parquet. but these might be superseded then by what martin uploaded?

**Comment by jGaboardi** [comment]
> archeology details: that was me who uploaded the .parquet ones, at some earlier iteration (for the feature matching). i got them from the gdrive and extracted only the "final version" layer before saving to parquet. but these might be superseded then by what martin uploaded?

So how about I just take those ones in this PR > change directory > convert to `.parquet`

**Comment by martinfleis** [comment]
Those uploaded here are most likely exactly the same as those @anastassiavybornova uploaded before.

**Comment by jGaboardi** [comment]
@anastassiavybornova @martinfleis Let's get yalls eyes on this for approval before merging.

**Review by anastassiavybornova — APPROVED** [review]

**Pull request merged**
