### PR TITLE
clean up relic dependencies

### LINKED ISSUE #204: revisit required Python & dependencies
* revisit required Python & dependencies
* xref #190

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR:
* (maybe?) resolves #204
* please be patient if I did some incorrectly with `pixie` – trying to learn

### CODE REVIEW

**Review by anastassiavybornova — COMMENTED** [review]
* pixi.lock env : i tried it out (with the neatnet notebook) and it's working for me! 
* pyproject.toml: i guess some of packages currently removed by this PR should stay if we stick to what martin suggests here #204 ?

**Comment by jGaboardi** [comment]
I'll update based on [new decisions](https://github.com/uscuni/simplification/issues/204#issuecomment-2525340803)

**Comment by jGaboardi** [comment]
Yeah... I tried to clean up merge conflicts in the `pixi.lock` file. Did not go well.

**Review by anastassiavybornova — APPROVED** [review]
ok so i re-tried with the new `pixi` environment, and it seems to be working for me, osmnx notebook runs for all cities, and the neatnet simplification notebook worked for aleppo AND wuhan (is this weird or expected? given https://github.com/uscuni/neatnet/issues/149 )

**Comment by martinfleis** [comment]
I am able to reproduce https://github.com/uscuni/neatnet/issues/149 with this PR. I suppose it is some pesky Apple Silicon issue again.

**Pull request merged**
